package com.doinglab.sangsik.api.domains.food.entity

import com.doinglab.sangsik.api.domains.food.dto.request.RequestPostFoodCustomDto
import jakarta.persistence.Entity
import jakarta.persistence.Id

@Entity(name = "FoodInfoR2")
class FoodInfoR2(
    @Id
    val foodNumber: Long,
    val predictKey: String? = "",
    val priority: Int? = 0,
    val relatedKeyword: String? = "",
    val foodType: String? = "",
    val koName: String? = "",
    val enName: String? = "",
    val jaName: String? = "",
    val country: String,
    val manufacturer: String? = null,
    val unit: String,
    val servingSize: Double,
    val totalServingSize: Double,
    val servingUnit: String? = null,
    val servingUnitSub: String? = null,
    val totalGram: Double,
    val energy: Double,
    val carbohydrate: Double,
    val protein: Double,
    val fat: Double,
    val totalSugars: Double,
    val totalDietaryFiber: Double,
    val calcium: Double,
    val iron: Double,
    val magnesium: Double,
    val phosphorus: Double,
    val potassium: Double,
    val sodium: Double,
    val zinc: Double,
    val copper: Double,
    val manganese: Double,
    val selenium : Double,
    val molybdenum: Double,
    val iodine: Double,
    val retinol: Double,
    val betaCarotene: Double,
    val vitaminA: Double,
    val thiamin: Double,
    val riboflavin: Double,
    val niacin: Double,
    val vitaminB6: Double,
    val biotin: Double,
    val totalFolate: Double,
    val vitaminC: Double,
    val vitaminD: Double,
    val vitaminE: Double,
    val vitaminK: Double,
    val isoleucine: Double,
    val leucine: Double,
    val valine: Double,
    val bcaa: Double,
    val cholesterol: Double,
    val saturatedFattyAcid: Double,
    val epa: Double,
    val dha: Double,
    val omega3FattyAcid: Double,
    val omega6FattyAcid: Double,
    val transFattyAcid: Double,
    val allulose: Double,
    val erythritol: Double,
    val sugarAlcohol: Double
) {
    data class Dto(
        val foodNumber: Long,
        val predictKey: String? = "",
        val priority: Int? = 0,
        val relatedKeyword: String? = "",
        val foodType: String? = "",
        val koName: String? = "",
        val enName: String? = "",
        val jaName: String? = "",
        val country: String? = "korea",
        val manufacturer: String? = null,
        val unit: String? = "g",
        val servingSize: Double? = -1.0,
        val totalServingSize: Double? = -1.0,
        val servingUnit: String? = null,
        val servingUnitSub: String? = null,
        val totalGram: Double? = -1.0,
        val energy: Double? = -1.0,
        val carbohydrate: Double? = -1.0,
        val protein: Double? = -1.0,
        val fat: Double? = -1.0,
        val totalSugars: Double? = -1.0,
        val totalDietaryFiber: Double? = -1.0,
        val calcium: Double? = -1.0,
        val iron: Double? = -1.0,
        val magnesium: Double? = -1.0,
        val phosphorus: Double? = -1.0,
        val potassium: Double? = -1.0,
        val sodium: Double? = -1.0,
        val zinc: Double? = -1.0,
        val copper: Double? = -1.0,
        val manganese: Double? = -1.0,
        val selenium : Double? = -1.0,
        val molybdenum: Double? = -1.0,
        val iodine: Double? = -1.0,
        val retinol: Double? = -1.0,
        val betaCarotene: Double? = -1.0,
        val vitaminA: Double? = -1.0,
        val thiamin: Double? = -1.0,
        val riboflavin: Double? = -1.0,
        val niacin: Double? = -1.0,
        val vitaminB6: Double? = -1.0,
        val biotin: Double? = -1.0,
        val totalFolate: Double? = -1.0,
        val vitaminC: Double? = -1.0,
        val vitaminD: Double? = -1.0,
        val vitaminE: Double? = -1.0,
        val vitaminK: Double? = -1.0,
        val isoleucine: Double? = -1.0,
        val leucine: Double? = -1.0,
        val valine: Double? = -1.0,
        val bcaa: Double? = -1.0,
        val cholesterol: Double? = -1.0,
        val saturatedFattyAcid: Double? = -1.0,
        val epa: Double? = -1.0,
        val dha: Double? = -1.0,
        val omega3FattyAcid: Double? = -1.0,
        val omega6FattyAcid: Double? = -1.0,
        val transFattyAcid: Double? = -1.0,
        val allulose: Double? = -1.0,
        val erythritol: Double? = -1.0,
        val sugarAlcohol: Double? = -1.0,
        val userId: Long? = 0L,
        val deleteFlag: Boolean? = false
    ) {
        fun toCustomEntity(userId: Long) = FoodInfoCustom(foodNumber, userId, "", "", predictKey, priority, relatedKeyword, koName, foodType, manufacturer, enName, "", jaName, 0, "", servingUnit, "", unit, totalGram, energy, carbohydrate, totalSugars, protein, fat, saturatedFattyAcid, transFattyAcid, cholesterol, sodium, totalDietaryFiber, calcium, vitaminA, thiamin, vitaminC, vitaminD, vitaminE, deleteFlag)

        fun toCopy(request: RequestPostFoodCustomDto) = copy(
            koName = request.foodName,
            manufacturer = request.manufacturer,
            unit = request.unit?.code,
            servingUnit = request.standardUnit,
            energy = request.calorie,
            sodium = request.sodium,
            totalSugars = request.sugar,
            protein = request.protein,
            calcium = request.calcium,
            cholesterol = request.cholesterol,
            fat = request.fat,
            carbohydrate = request.carbonhydrate,
            saturatedFattyAcid = request.saturatedFat,
            transFattyAcid = request.transFat,
            totalDietaryFiber = request.dietaryFiber,
            vitaminA = request.vitaminA,
            thiamin = request.vitaminB,
            vitaminC = request.vitaminC,
            vitaminD = request.vitaminD,
            vitaminE = request.vitaminE,
            totalGram = request.totalGram
        )
    }

    fun toDto() = Dto(foodNumber, predictKey, priority, relatedKeyword, foodType, koName, enName, jaName, country, manufacturer, unit, servingSize, totalServingSize, servingUnit, servingUnitSub, totalGram, energy, carbohydrate, protein, fat, totalSugars, totalDietaryFiber, calcium, iron, magnesium, phosphorus, potassium, sodium, zinc, copper, manganese, selenium, molybdenum, iodine, retinol, betaCarotene, vitaminA, thiamin, riboflavin, niacin, vitaminB6, biotin, totalFolate, vitaminC, vitaminD, vitaminE, vitaminK, isoleucine, leucine, valine, bcaa, cholesterol, saturatedFattyAcid, epa, dha, omega3FattyAcid, omega6FattyAcid, transFattyAcid, allulose, erythritol, sugarAlcohol)
}
